### ISSUE TITLE
examples/upskirt.c fails to build with gcc 4.5.2

### ISSUE THREAD

**Issue by simcop2387** [vmg/sundown#32]
gcc -c -g -O3 -Wall -Werror -Isrc -Ihtml -fPIC   -c -o examples/upskirt.o examples/upskirt.c
cc1: warnings being treated as errors
examples/upskirt.c: In function ‘main’:
examples/upskirt.c:71:8: error: ignoring return value of ‘fwrite’, declared with attribute warn_unused_result

simple to work around, but should likely do some real checking

**Comment by vmg** [comment]
Fixed! Sorry for the delay.
